### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by HOD42** [nophead/EnviroPlusWeb#1] opened 2020-01-07 00:16 UTC
Running app.py I get the following:

pi@raspberrypi:~/EnviroPlusWeb $ sudo python3 /home/pi/EnviroPlusWeb/app.py
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/EnviroPlusWeb/app.py", line 209, in background
    display_everything()
  File "/home/pi/EnviroPlusWeb/app.py", line 98, in display_everything
    last_values = days[-1][-1]
IndexError: list index out of range

I can browse to the page and see a single set of readings but all the PM values are 0.

**Comment by nophead** [comment] 2020-01-08 11:02
The problem is caused by trying to display data on the LCD before any has been gathered. It is hard for me to test that as I had months of data before I added the display code. I have pushed a commit which I think will fix it. Nothing will be displayed for the first 5 minutes.

**Comment by HOD42** [comment] 2020-01-08 23:12
Cool! I wondered if it was something like that (was trying to fathom how to initialise some fake data). I'll give it a go and let you know.

**Comment by nophead** [comment] 2020-01-09 12:51
Should be fixed by the commit I just did. I have tested it this time!

**Comment by HOD42** [comment] 2020-01-09 13:41
Confirmed working, thanks!

**Closed** 2020-01-09 13:42 UTC
